FROM redhat/ubi8-minimal


ENV NODEJS_VERSION=18
ENV PATH="${PATH}:/opt/bin"
ENV PATH="${PATH}:/opt/app-root/bin"
# COPY utils/install-npm.sh install-npm.sh



RUN  microdnf update 

RUN microdnf install scl-utils tar

# install python essentials
RUN microdnf --nodocs -y  install python3-pip python3-wheel python3-setuptools

RUN python3 -m pip install --upgrade pip

# install npm via https://github.com/stolostron/common-nodejs-parent
RUN echo -e "[nodejs]\nname=nodejs\nstream=${NODEJS_VERSION}\nprofiles=\nstate=enabled\n" > /etc/dnf/modules.d/nodejs.module
RUN microdnf install nodejs npm
# RUN ./install-npm.sh

#nodig voor mod_wsgi dat kan vast handiger
RUN microdnf install httpd  httpd-devel gcc redhat-rpm-config python3-devel

RUN microdnf  --nodocs -y install curl

RUN microdnf clean all

WORKDIR /opt/s2i

COPY .s2i/bin .

WORKDIR /opt/builder

COPY builder .

WORKDIR /opt/config

COPY config .

WORKDIR /opt/gateway

COPY gateway .

WORKDIR /opt/scripts

COPY scripts .

WORKDIR /opt/supervisor

COPY supervisor .

# TODO: oplossen dat we niet instaleren op /.npm
WORKDIR /.npm
RUN chown 1001:0 /.npm
# /TODO

RUN chown -R 1001 /opt
RUN chgrp -R 0 /opt
RUN chmod -R g+w /opt


USER 1001

LABEL io.k8s.description="S2I builder for custom Jupyter notebooks." \
      io.k8s.display-name="Jupyter Notebook" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="builder,jupyter" \
      io.openshift.s2i.scripts-url="image:///opt/app-root/builder"

WORKDIR /opt/s2i




RUN ./assemble


CMD [ "/opt/app-root/builder/run" ]
# 