FROM redhat/ubi8-minimal

USER root 

# install python essentials
RUN  microdnf update && microdnf --nodocs -y  install python3-pip python3-wheel python3-setuptools\
  && microdnf clean all

# install npm
RUN microdnf  --nodocs -y install nodejs

COPY . /tmp

# RUN /bin/bash 

RUN chown -R 1001 /tmp && \
    chgrp -R 0 /tmp && \
    chmod -R g+w /tmp && \    
    mv /tmp/s2i/bin /tmp/scripts

USER 1001

LABEL io.k8s.description="S2I builder for custom Jupyter notebooks." \
      io.k8s.display-name="Jupyter Notebook" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="builder,jupyter" \
      io.openshift.s2i.scripts-url="image:///opt/app-root/builder"


RUN /tmp/scripts/assemble

CMD [ "/opt/app-root/builder/run" ]
# 